project_id = "nqxsfmnvdfdfvndrodvs"

[functions.calculate-assembly-radius]
verify_jwt = false

[functions.check-assembly-eligibility]
verify_jwt = false

[functions.geocode-postcode]
verify_jwt = false

[functions.send-document-reminders]
verify_jwt = false

[functions.docuseal-create-submission]
verify_jwt = true

[functions.docuseal-webhook]
verify_jwt = false