// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqxsfmnvdfdfvndrodvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xeHNmbW52ZGZkZnZuZHJvZHZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMjc0MTksImV4cCI6MjA3MjcwMzQxOX0.XohXpJo_kwqtL7fgRbITjW6cq_atc97V6PfUArks-t0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});